services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8081"
    restart: unless-stopped
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - mongodb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./static:/app/static
      - ./docs:/app/docs

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
networks:
  mynet:
    driver: bridge
volumes:
  mongo_data: