services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8081"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/server", "-ping" ]
      interval: 30s
      timeout: 3s
      start_period: 5s

  mongo:
    image: mongo:8
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: