basePath: /
definitions:
  github_com_sarff_go-robotdreams-diplom_internal_models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_sarff_go-robotdreams-diplom_internal_models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
host: 127.0.0.1
info:
  contact: {}
  description: Boom boom — and into production.
  title: Shat API
  version: 0.001.001
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифікація користувача та отримання токена
      parameters:
      - description: Дані для входу
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sarff_go-robotdreams-diplom_internal_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Користувач та токен
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Невірний логін або пароль
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вхід користувача
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Створення облікового запису користувача
      parameters:
      - description: Дані для реєстрації
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sarff_go-robotdreams-diplom_internal_models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Статус успішної реєстрації
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Невірні дані
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Реєстрація нового користувача
      tags:
      - auth
securityDefinitions:
  UserTokenAuth:
    in: header
    name: X-User-Token
    type: apiKey
swagger: "2.0"
