basePath: /
definitions:
  models.CreateRoomRequest:
    properties:
      description:
        type: string
      members:
        description: dive - перевірити кожен елемент масиву
        items:
          type: string
        minItems: 1
        type: array
      name:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - members
    - name
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      room_id:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: string
    type: object
  models.MessageRequest:
    properties:
      content:
        type: string
      room_id:
        type: string
    required:
    - content
    - room_id
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.Room:
    properties:
      created_at:
        type: string
      creator_id:
        type: string
      description:
        type: string
      id:
        type: string
      last_message:
        $ref: '#/definitions/models.Message'
      members:
        items:
          type: string
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_online:
        type: boolean
      last_seen:
        type: string
      updated_at:
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - username
    type: object
host: 127.0.0.1
info:
  contact: {}
  description: Boom boom — and into production.
  title: Shat API
  version: 0.001.001
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифікація користувача та отримання токена
      parameters:
      - description: Дані для входу
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Користувач та токен
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Невірний логін або пароль
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вхід користувача
      tags:
      - auth
  /api/v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Отримати інформацію про поточного автентифікованого користувача
      produces:
      - application/json
      responses:
        "200":
          description: Профіль користувача
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Користувача не знайдено
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Отримати профіль користувача
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Створення облікового запису користувача
      parameters:
      - description: Дані для реєстрації
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Статус успішної реєстрації
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Невірні дані
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Реєстрація нового користувача
      tags:
      - auth
  /api/v1/chat/id/{roomID}:
    get:
      consumes:
      - application/json
      description: Отримати інформацію про кімнату за її ID
      parameters:
      - description: ID кімнати
        in: path
        name: roomID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Кімната
          schema:
            $ref: '#/definitions/models.Room'
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Кімната не знайдена
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Отримати кімнату по ID
      tags:
      - chat
  /api/v1/chat/messages:
    post:
      consumes:
      - application/json
      description: Відправка повідомлення в канал/room
      parameters:
      - description: Дані для відправки повідомлення
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.MessageRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Помилка валідації або бізнес-логіки
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Відправити повідомлення
      tags:
      - chat
  /api/v1/chat/rooms:
    get:
      consumes:
      - application/json
      description: Повертає список кімнат, в яких присутній авторизований користувач
      produces:
      - application/json
      responses:
        "200":
          description: Список кімнат
          schema:
            items:
              $ref: '#/definitions/models.Room'
            type: array
        "400":
          description: Не вдалося отримати кімнати
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Отримати всі кімнати користувача
      tags:
      - chat
    post:
      consumes:
      - application/json
      description: Створення кімнати для спілкування
      parameters:
      - description: Дані для створення
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateRoomRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Помилка валідації або бізнес-логіки
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Створення кімнати
      tags:
      - chat
  /api/v1/chat/rooms/{roomName}:
    get:
      consumes:
      - application/json
      description: Отримати інформацію про кімнату за її Name
      parameters:
      - description: Name кімнати
        in: path
        name: roomName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Кімната
          schema:
            $ref: '#/definitions/models.Room'
        "401":
          description: Неавторизований доступ
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Кімната не знайдена
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - UserTokenAuth: []
      summary: Отримати кімнату по Name
      tags:
      - chat
securityDefinitions:
  UserTokenAuth:
    in: header
    name: X-User-Token
    type: apiKey
swagger: "2.0"
